version: 3

pullapprove_conditions:
    - condition: "base.ref != 'master'"
      unmet_status: failure
      explanation: 'Base branch cannot be the master branch'
    - condition: 'commits == 1'
      unmet_status: failure
      explanation: 'PR must be squashed into one commit.'

notifications:
    - when: pullapprove.started
      comment: >
          Hey @{{ author }},
          
          Please ensure your build is available at [https://{{ user.username }}.github.io/{{ head.repo.name }}/{{ head.sha }}/enhancedTable/samples/et-index.html](https://{{ user.username }}.github.io/{{ head.repo.name }}/{{ head.sha }}/enhancedTable/samples/et-index.html)


          Thanks for the PR!
    - when: pullapprove.approved
      comment: 'The review is completed.'

groups:
    sanity:
        reviewers:
            users:
                - dane-thomas
                - ShrutiVellanki
                - james-rae
        reviews:
            required: 2
            request: 3
            request_order: given

    code:
        conditions:
            - "'sanity' in groups.approved"
        reviewers:
            users:
                - milesap
                - spencerwahl
                - AleksueiR
        reviews:
            required: 1
            request: 2
            request_order: given
